alpha/takim/urls.py
from django.urls import path
from .views import base,takim_list,takim_ekle,takim_guncelle,sporcu_list,sporcu_ekle,sporcu_guncelle,antrenman_list,antrenman_ekle,antrenman_guncelle,haftalik_antrenman,antrenman_yap
from .views import gunluk_ekle,htmx_sporcu_ekle,yaris_list,sporcu_detail

urlpatterns = [
    path('',base,name='takim'),
    path('takimlar/',takim_list,name='takim_list'),
    path('takim_ekle/',takim_ekle,name='takim_ekle'),
    path('takim_guncelle/<int:id>/',takim_guncelle,name='takim_guncelle'),
    path('sporcular/',sporcu_list,name='sporcu_list'),
    path('sporcu_ekle/',sporcu_ekle,name='sporcu_ekle'),
    path('sporcu_guncelle/<int:id>/',sporcu_guncelle,name='sporcu_guncelle'),
    path('antrenman/',antrenman_list,name='antrenman_list'),
    path('antrenman_ekle/',antrenman_ekle,name='santrenman_ekle'),
    path('antrenman_guncelle/<int:id>/',antrenman_guncelle,name='antrenman_guncelle'),
    path('haftalik/',haftalik_antrenman,name='haftalik_list'),


    path('antrenman_yap/',antrenman_yap,name='antrenman'),
    path('gunluk_ekle/',gunluk_ekle,name='gunluk_ekle'),
    path('htmx_sporcu_ekle/',htmx_sporcu_ekle,name='htmx_sporcu_ekle'),


    path('yarislar/',yaris_list,name='yaris_list'),
    path('sporcu_detail/<int:sporcu_id>',sporcu_detail,name='sporcu_detail'),


]

alpha/takim/models.py
from django.db import models
from main.models import Antrenor
from datetime import date

# Create your models here.


DAY_OF_WEEKS_CHOICES = (
    
    (1,"Pazartesi"),
    (2,"Salı"),
    (3,"Çarsamba"),
    (4,"Perşembe"),
    (5,"Cuma"),
    (6,"Cumartesi"),
    (8, "Pazar"),
  
)
ANTRENMAN_YERI = (
    ('Hacettepe', "Hacettepe"),
    ('Atlas', "Atlas"),
)
ANTRENMAN_TURU = (
    ('Yüzme', "Yüzme"),
    ('Kara', "Kara"),
)
CINSIYET = (
    ('Erkek', "Erkek"),
    ('Kadın', "Kadın"),
)

class Takim (models.Model):
    adi=models.CharField(max_length=30)
    antrenor=models.ManyToManyField(Antrenor)
    resim=models.ImageField(null=True,blank=True)
    aktif=models.BooleanField(default=True)
    def __str__(self):
        return self.adi

class Sporcu (models.Model):
    adi=models.CharField(max_length=30)
    soyadi=models.CharField(max_length=30)
    anne=models.CharField(max_length=30)
    baba=models.CharField(max_length=30)
    cinsiyet=models.CharField(max_length=30,choices=CINSIYET)
    dogum_tarihi=models.DateField()
    okulu=models.CharField(max_length=30)
    resim=models.ImageField(upload_to='media/')
    telefon=models.CharField(max_length=10)
    telefon_veli=models.CharField(max_length=10)
    aktif=models.BooleanField(default=True)
    takim=models.ForeignKey(Takim,on_delete=models.CASCADE)
    def __str__(self):
        return self.adi +' '+ self.soyadi

class Ozellikler(models.Model):
    boy=models.IntegerField()
    kilo=models.IntegerField()
    tarih=models.DateField(auto_now_add=True)
    sporcu=models.ForeignKey(Sporcu,on_delete=models.CASCADE)


class HaftalikAntrenman(models.Model):
    dayofweek=models.IntegerField(choices=DAY_OF_WEEKS_CHOICES)
    baslangic=models.TimeField()
    bitis=models.TimeField(null=True)
    takim=models.ForeignKey(Takim,on_delete=models.CASCADE)
    yer=models.TextField(choices=ANTRENMAN_YERI,null=True)
    tur=models.TextField(choices=ANTRENMAN_TURU,null=True)
  
    def __str__(self):
        return str(self.dayofweek)

class Antrenman(models.Model):
    gun=models.DateField(auto_now_add=True)
    takimlar=models.ManyToManyField(Takim)
    sporcular=models.ManyToManyField(Sporcu,null=True,blank=True)
    mesafe=models.IntegerField(default=0)

    class Meta:
        ordering=['-gun']

class Yarislar(models.Model):
    yaris=models.CharField(max_length=100)
    sehir=models.CharField(max_length=100)
    tarih=models.DateField()
    cinsiyet=models.CharField(max_length=100)
    mesafe=models.CharField(max_length=100)
    brans=models.CharField(max_length=100)
    kategori=models.CharField(max_length=100)
    siralama=models.CharField(max_length=100)
    sporcu=models.CharField(max_length=100)
    yas=models.IntegerField()
    takim=models.CharField(max_length=100)
    zaman=models.TimeField()
    puan=models.CharField(max_length=100)
    sporcu_id=models.ForeignKey(Sporcu,on_delete=models.CASCADE)

    def __str__(self):
        return self.yaris +'-'+ self.mesafe +self.brans


class Barajlar (models.Model):
    yaris=models.CharField(max_length=100)
    sehir=models.CharField(max_length=100)
    tarih=models.DateField(max_length=100)
    cinsiyet=models.CharField(max_length=100)
    mesafe=models.CharField(max_length=100)
    brans=models.CharField(max_length=100)
    yas=models.IntegerField()
    baraj_turu=models.CharField(max_length=100)
    baraj=models.TimeField()

    def __str__(self):
        return self.sehir+ '-'+ self.cinsiyet +'-'+  self.mesafe +'-'+  self.brans

alpha/takim/templates/_base_takim.html
{% load compress %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fk Alpha Academy</title>
<meta name="keywords" content="özel yüzme dersi, Ankara yüzme kursu, yüzme eğitimi, yüzme teknikleri stilleri, yüzme havuzu, yüzme antremanı, yüzme antrenörü, yarışlar, reglemanlar">
		<meta name="description" content="Başkent Ankara Ümitköyde profosyonel yüzme sporcusu yetiştiren FK ALpha Academy'de, özel yüzme dersi, performans yüzme, takım yüzme, vip yüzme eğitimleri verilmektedir." />
		<script src="https://unpkg.com/htmx.org@2.0.4"></script>
    {% compress css %}
    <link rel="stylesheet" href="{% static 'src/output.css' %}">
    {% endcompress %}
     <title>fkalphaacademy, profosyonel yüzme sporcusu yetiştiren spor kulübü.</title> 


</head>




<body class=" bg-gray-200">


    <nav class="bg-white dark:bg-gray-900 fixed w-full z-20 top-0 start-0 border-b border-gray-200 dark:border-gray-600">
        <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="{% url "takim" %}" class="flex items-center space-x-3 rtl:space-x-reverse">
            <img src="/media/logo.jpeg" class="h-8" alt="Flowbite Logo">
            <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">FK Alpha Academy Takimlar</span>
        </a>
        <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">

            <button data-collapse-toggle="navbar-sticky" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2
             focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-sticky" aria-expanded="false">
              <span class="sr-only">Open main menu</span>
              <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
              </svg>
          </button>
        </div>
        <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-sticky">
          <ul class="flex flex-col p-4 md:p-0 mt-4 font-medium border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
            <li>
              <a href="{% url "antrenman_list" %}" class="block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500" aria-current="page">Antrenman</a>
            </li>
            <li>
              <a href="{% url "takim_list" %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent
               md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700
                dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Takim</a>
            </li>
            <li>
              <a href="{% url "sporcu_list" %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent
               md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700
                dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Sporcu</a>
            </li>

          </ul>
        </div>
        </div>
      </nav>
      
    <!-- Navigation -->
  


    <div class="container mx-auto">




        {% block content %}


        {% endblock %}
    </div>


    <script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></script>
</body>

</html>

alpha/takim/templates/antrenman.html
{% extends "_base_takim.html" %}
{% load account_tags %}
{% block content %}

<<<<<<< HEAD
<script src="https://unpkg.com/htmx.org@2.0.4"
    integrity="sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+"
    crossorigin="anonymous"></script>
=======
<<<<<<< HEAD
<div class=" mb-2 bg-gray-50 justify-center text-center pt-20 shadow-2xl shadow-blue-400">

    <h2 class="pt-6 text-center  text-2xl tracking-tight font-bold text-gray-900 dark:text-white">Takimlar</h2>

</div>
<div class="flex justify-center pt-6 ">
    <a href="/takim/takim_ekle">
        <button type="submit"
            class="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700">Yeni
            Ekle</button>

    </a>
</div>





<div class="grid grid-cols-7">
    {% for gun,ant in haftalik_nested.items%}
    <div class=" grid-rows-10 gap-2 m-2 justify-between bg-blue-300 rounded-md ">
        <div class="font-bold text-center">{{gun}}</div>

        <div class="row-span-3">
            {% for antrenman in ant.sabah %}
            <div class=" bg-blue-300 ">

                <span class="font-semibold">{{antrenman.get_yer_display}}</span><br>
                {{antrenman.tur}}-
                {{antrenman.baslangic}}
                {{antrenman.bitis}}

            </div>
            {% endfor %}
        </div>
        <div class=" w-full bg-blue-800 h-4"></div>

        <div class="row-span-3">
            {% for antrenman in ant.aksam %}
            <div class=" bg-blue-300">

                <span class="font-semibold">{{antrenman.get_yer_display}}</span><br>
                {{antrenman.tur}}-
                {{antrenman.baslangic}}
                {{antrenman.bitis}}

            </div>
            {% endfor %}
        </div>
    </div>




    {% endfor %}
</div>
=======
<script src="https://unpkg.com/htmx.org@2.0.4" integrity="sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+" crossorigin="anonymous"></script>    
>>>>>>> kontrol

<div class=" mb-2 bg-gray-50 justify-center text-center pt-20 shadow-2xl shadow-blue-400">

    <h2 class="pt-6 text-center  text-2xl tracking-tight font-bold text-gray-900 dark:text-white">Antremana Basla</h2>

</div>



<div class="row-span-3">
    {% for antrenman in gunluk_antrenman%}
    <div class=" bg-blue-300 ">

        <span class="font-semibold">{{antrenman.takim.adi}}</span><br>
        <span class="font-semibold">{{antrenman.get_yer_display}}</span><br>
        {{antrenman.tur}}-
        {{antrenman.baslangic}}
        {{antrenman.bitis}}

        <button
            class="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700"
            hx-vals='{"antrenman":"{{antrenman.takim.id}}"}' hx-post="{% url 'gunluk_ekle' %}" hx-trigger="click"
            hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}' hx-target="#takim">
            Başlat

        </button>


    </div>
    {% endfor %}
</div>
<div class="grid-rows-2 gap-10">
    <div>
        <h1 class="block bg-red-400 text-lg font-semibold text-center">Bekleyenler</h1>

<<<<<<< HEAD
        <div class="flex m-6 justify-center items-center" id="takim"></div>
    </div>


    <div>
        <h1 class="block bg-green-400 text-lg font-semibold text-center">Gelenler</h1>

        <div class="flex m-6 justify-center items-center" id="giren"></div>
    </div>
</div>
=======
>>>>>>> da9b8a88fc1954b0ba7d7f79a9fecb38544281da
>>>>>>> kontrol

{% endblock content %}

alpha/takim/templates/grafik.html
<canvas id="myChart" style="width:100%;max-width:700px"></canvas>

<script>
    const xValues = {{ xValues| safe }};
    const yValues = {{ yValues|safe }};

    new Chart("myChart", {
        type: "line",
        data: {
            labels: xValues,
            datasets: [{
                fill: false,
                lineTension: 0,
                backgroundColor: "rgba(0,0,255,1.0)",
                borderColor: "rgba(0,0,255,0.1)",
                data: yValues
            }]
        },
        options: {
            legend: { display: false },
            scales: {   
                xAxes: [{}],
                yAxes: [{ ticks: { reverse: true ,  } }],
            }
        }
    });
</script>

alpha/takim/templates/grafik11.html
<div id="xValues">{{xValues}}</div>
<div id="yValues">{{yValues}}</div>

alpha/takim/templates/sporcu_detail copy 2.html
{% extends "_base_takim.html" %}
{% load account_tags %}
{% block content %}





<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>




<div class="pt-6 flex w-full justify-center items-center">
    <div class="inline-grid w-full">
        <div class="w-full md:w-6/12 lg:w-3/12 lg:mb-0 mb-12  pt-24">
            <div class="px-6">
            <img src="{{sporcu.resim.url}}" alt="{{antrenor}}" class="shadow-lg rounded-full w-24 h-24 mx-auto"
                style="max-width: 120px;" />
            <div class="pt-6 text-center">
                <h5 class="text-xl font-bold">{{sporcu.adi}} {{sporcu.soyadi}}</h5>
        
                <div class="mt-6">
                <button class="bg-blue-400 text-white w-8 h-8 rounded-full outline-none focus:outline-none mr-1 mb-1"
                    type="button">
                    <i class="fab fa-twitter"></i></button><button
                    class="bg-blue-600 text-white w-8 h-8 rounded-full outline-none focus:outline-none mr-1 mb-1"
                    type="button">
                    <i class="fab fa-facebook-f"></i></button><button
                    class="bg-pink-500 text-white w-8 h-8 rounded-full outline-none focus:outline-none mr-1 mb-1"
                    type="button">
                    <i class="fab fa-dribbble"></i>
                </button>
                </div>
            </div>
            </div>
        </div>
        <div class="flex w-full shadow-md sm:rounded-lg justify-center">
            <table class=" w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-6 py-3">
                            Branş-Mesafe
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Best Time
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Son Yarış
                        </th>
                    </tr>
                </thead>


                <tbody>


                    {% for yaris in yaris_list %}
                    
                    <tr
                    onclick="loadChart({{yaris.xValues}},{{yaris.yValues}},'{{yaris.brans}} - {{yaris.mesafe}}','{{yaris.total|slice:"3:11"}}')"
                    data-modal-target="popup-modal" data-modal-toggle="popup-modal"
                    class="w-full max-h-20 bg-white border-b focus:bg-gray-500 dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">

                       
                        <td class="px-2 max-w-20 flex-wrap">{{yaris.brans}} {{yaris.mesafe}}</td>
                        <td class="px-2 max-w-20 flex-wrap">{{yaris.total|slice:"3:11"}}</td>
                        <td class="px-2 max-w-20 flex-wrap">{{yaris.best_tarih|slice:"0:11" }}</td>

              

                    </tr>
                
                    {% endfor %}
                </tbody>
            </table>
            <div id="popup-modal" tabindex="-1"
                class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
                <div class="relative p-4 w-full max-w-md max-h-full">

                    <div class="relative border-spacing-3 bg-gradient-to-b from-slate-100 via-zinc-200 to-slate-100 rounded-lg shadow-sm dark:bg-gray-700">

                        <div class="p-4 md:p-5 text-center">
                            <h1>{{sporcu.adi}} {{sporcu.soyadi}}
                                 <br> <span id="brans_mesafe"></span>
                                 <br> <span class="text-red-500 text-xl font-bold" id="best_time"></span>
                            
                            
                            </h1>
            
                        </div>
                        <div id="graph_container">
                            <canvas id="myChart" style="width:100%;max-width:700px"></canvas>
                        </div>
                        <script>



                            function loadChart(xValues, yValues, brans,best_time) {
                                document.getElementById('brans_mesafe').innerText = brans
                                document.getElementById('best_time').innerText = best_time

                                var appended = document.createElement('canvas'); // is a node
                                appended.style.cssText = "width:100%;max-width:700px"
                                appended.id = 'myChart'
                                document.getElementById('myChart').remove(); // this is my <canvas> element
                                const graph_container = document.getElementById('graph_container');
                                graph_container.appendChild(appended);

                                new Chart("myChart", {
                                    type: "line",

                                    data: {
                                        labels: xValues,
                                        datasets: [{
                                            borderColor: 'rgba(75, 192, 192, 1)',
                                            backgroundColor: 'rgba(75, 192, 192, 0.2)',
                                            borderWidth: 2,
                                            fill: 'start',
                                            data: yValues
                                        }]
                                    },
                                    options: {
                                        legend: { display: false },
                                        scales: {
                                            xAxes: [{}],
                                            yAxes: [{ ticks: { reverse: true, } }],
                                        }
                                    }
                                });
                            }

                        </script>

                        <div class="p-4 md:p-5 text-center">


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>







    {% endblock content %}

alpha/takim/templates/sporcu_detail copy.html
{% extends "_base_takim.html" %}
{% load account_tags %}
{% block content %}





<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>




<div class="pt-24">
    <div class="flex overflow-x-auto shadow-md sm:rounded-lg">
        <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                    <th scope="col" class="px-6 py-3">
                        Branş-Mesafe
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Best Time
                    </th>

                    <th scope="col" class="px-6 py-3">
                        <span class="sr-only">Guncelle</span>
                    </th>
                </tr>
            </thead>


            <tbody>


                {% for yaris in yaris_list %}

                <tr
                    class="relative max-h-20 bg-white border-b focus:bg-gray-500 dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">


                    <td class="px-2 py-4 max-w-20 flex-wrap">{{yaris.brans}} {{yaris.mesafe}}</td>
                    <td class="px-2 py-4 max-w-20 flex-wrap">{{yaris.total|slice:"3:11"}} <br> {{yaris.best_tarih |slice:"0:11"}}</td>
                    <td class="px-2 py-4 max-w-20 flex-wrap">


                        <button onclick="loadChart{{forloop.counter}}()" data-modal-target="popup-modal{{forloop.counter}}" data-modal-toggle="popup-modal{{forloop.counter}}" class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" type="button">
                            Grafik
                            </button>
                            <div id="popup-modal{{forloop.counter}}" tabindex="-1" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
                                <div class="relative p-4 w-full max-w-md max-h-full">
                                   
                                    <div class="relative bg-slate-200 rounded-lg shadow-sm dark:bg-gray-700">

                                        <div class="p-4 md:p-5 text-center">

                                            <button data-modal-hide="popup-modal{{forloop.counter}}" type="button" 
                                            class="py-2.5 px-5 ms-3 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">
                                            {{sporcu.adi}} {{sporcu.soyadi}} <br> {{yaris.mesafe}} {{yaris.brans}} {{yaris.total|slice:"3:11"}} </button>
                                        </div>
                                        <canvas id="myChart{{forloop.counter}}" style="width:100%;max-width:700px"></canvas>

                                                <script>

                                                    
                                                    const xValues{{forloop.counter}} = {{ yaris.xValues| safe }};
                                                    const yValues{{forloop.counter}} = {{ yaris.yValues|safe }};
                                                    function loadChart{{forloop.counter}}() {
                                                        console.log('aaa')
                                                        new Chart("myChart{{forloop.counter}}", {
                                                        type: "line",
                                                        data: {
                                                            labels: xValues{{forloop.counter}},
                                                            datasets: [{
                                                                fill: false,
                                                                lineTension: 0,
                                                                backgroundColor: "rgba(0,0,255,1.0)",
                                                                borderColor: "rgba(0,0,255,0.1)",
                                                                data: yValues{{forloop.counter}}
                                                            }]
                                                        },
                                                        options: {
                                                            legend: { display: false },
                                                            scales: {   
                                                                xAxes: [{}],
                                                                yAxes: [{ ticks: { reverse: true ,  } }],
                                                            }
                                                        }
                                                    });
                                                            }
                                                  
                                                </script>

                                        <div class="p-4 md:p-5 text-center">

                          
                                        </div>
                                    </div>
                                </div>
                            </div>

                    </td>

                </tr>

                {% endfor %}
            </tbody>
        </table>

    </div>







    {% endblock content %}

alpha/takim/templates/sporcu_list.html
{% extends "_base_takim.html" %}
{% load account_tags %}
{% block content %}

<div class=" mb-2 bg-gray-50 justify-center text-center pt-20 shadow-2xl shadow-blue-400">

    <h2 class="pt-6 text-center  text-2xl tracking-tight font-bold text-gray-900 dark:text-white">Takimlar</h2>

</div>
<div class="flex justify-center pt-6 pb-6 ">
    <a href="{% url "sporcu_ekle" %}">
        <button type="submit"
            class="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700">Yeni
            Ekle</button>

    </a>
</div>
<div class="block w-full  shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-2">
                   
                </th>
                <th scope="col" class="px-2">
                    Adi Soyadi
                </th>
                <th scope="col" class="px-2">
                    Takimi
                </th>
                <th scope="col" class="px-2">
                    <span class="sr-only">Yarışlar</span>
                </th>
            </tr>
        </thead>
        <tbody>
            {% for sporcu in sporcu_list %}

            <tr
                class="relative max-h-20 bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                <th scope="row" class="flex p-2 items-center justify-center">
                    <img src="{{sporcu.resim.url}} " class="h-16 w-16" alt="{{sporcu.adi}} ">

                </th>
                <th scope="row" class="px-2 font-medium text-gray-900  dark:text-white">
                    {{sporcu.adi}} {{sporcu.soyadi}}
                </th>

                
                <td class="px-2">
                    {{sporcu.takim.adi}}
                </td>

                

                <td class="px-2 text-right">
                    <a href="/takim/sporcu_detail/{{sporcu.id}}"
                        class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Yarışlar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


{% endblock content %}